/**
 * Example invoices dataset (deterministic, seed 0)
 * 50 invoices total – types 1–5
 */

import { Invoice } from "src/types/database";
import { exampleContacts } from "./contacts";
import { anonymousContacts } from "./anonymousContacts";

export const exampleInvoices: Array<Invoice> = [
  // ─────────────────────────────
  // TYPE 5 – Initial stock corrections (no contacts)
  // ─────────────────────────────
  {
    number: "0001",
    type: 5,
    date_issue: "2025-05-01",
    note: "Initial inventory correction – Ponorná čerpadla series",
  },
  {
    number: "0002",
    type: 5,
    date_issue: "2025-05-02",
    note: "Initial inventory correction – Kalová čerpadla series",
  },
  {
    number: "0003",
    type: 5,
    date_issue: "2025-05-03",
    note: "Initial inventory correction – Zahradní čerpadla",
  },
  {
    number: "0004",
    type: 5,
    date_issue: "2025-05-04",
    note: "Initial inventory correction – Tlaková čerpadla",
  },
  {
    number: "0005",
    type: 5,
    date_issue: "2025-05-05",
    note: "Initial inventory correction – Cirkulační čerpadla",
  },
  {
    number: "0006",
    type: 5,
    date_issue: "2025-05-06",
    note: "Initial inventory correction – Příslušenství – hadice",
  },
  {
    number: "0007",
    type: 5,
    date_issue: "2025-05-07",
    note: "Initial inventory correction – Příslušenství – spínače",
  },
  {
    number: "0008",
    type: 5,
    date_issue: "2025-05-08",
    note: "Initial inventory correction – Příslušenství – nádoby",
  },
  {
    number: "0009",
    type: 5,
    date_issue: "2025-05-09",
    note: "Initial inventory correction – Příslušenství – měřidla",
  },
  {
    number: "0010",
    type: 5,
    date_issue: "2025-05-10",
    note: "Initial inventory correction – miscellaneous items",
  },

  // ─────────────────────────────
  // TYPE 1 – Buy Cash Invoices (Suppliers, cash)
  // ─────────────────────────────
  {
    number: "0011",
    type: 1,
    date_issue: "2025-05-11",
    date_tax: "2025-05-11",
    ico: exampleContacts[0].ico,
    modifier: exampleContacts[0].modifier,
    dic: exampleContacts[0].dic,
    company_name: exampleContacts[0].company_name,
    street: exampleContacts[0].street,
    city: exampleContacts[0].city,
    postal_code: exampleContacts[0].postal_code,
    phone: exampleContacts[0].phone,
    email: exampleContacts[0].email,
    note: "Buy cash – small batch of ponorná čerpadla",
  },
  {
    number: "0012",
    type: 1,
    date_issue: "2025-05-12",
    date_tax: "2025-05-12",
    ico: exampleContacts[1].ico,
    modifier: exampleContacts[1].modifier,
    dic: exampleContacts[1].dic,
    company_name: exampleContacts[1].company_name,
    street: exampleContacts[1].street,
    city: exampleContacts[1].city,
    postal_code: exampleContacts[1].postal_code,
    phone: exampleContacts[1].phone,
    email: exampleContacts[1].email,
    note: "Buy cash – kalová čerpadla 750 W stock replenishment",
  },
  {
    number: "0013",
    type: 1,
    date_issue: "2025-05-13",
    date_tax: "2025-05-13",
    ico: exampleContacts[2].ico,
    modifier: exampleContacts[2].modifier,
    dic: exampleContacts[2].dic,
    company_name: exampleContacts[2].company_name,
    street: exampleContacts[2].street,
    city: exampleContacts[2].city,
    postal_code: exampleContacts[2].postal_code,
    phone: exampleContacts[2].phone,
    email: exampleContacts[2].email,
    note: "Buy cash – accessories (batch of hadice and klapky)",
  },
  {
    number: "0014",
    type: 1,
    date_issue: "2025-05-14",
    date_tax: "2025-05-14",
    ico: exampleContacts[3].ico,
    modifier: exampleContacts[3].modifier,
    dic: exampleContacts[3].dic,
    company_name: exampleContacts[3].company_name,
    street: exampleContacts[3].street,
    city: exampleContacts[3].city,
    postal_code: exampleContacts[3].postal_code,
    phone: exampleContacts[3].phone,
    email: exampleContacts[3].email,
    note: "Buy cash – refill of garden pumps line",
  },
  {
    number: "0015",
    type: 1,
    date_issue: "2025-05-15",
    date_tax: "2025-05-15",
    ico: exampleContacts[4].ico,
    modifier: exampleContacts[4].modifier,
    dic: exampleContacts[4].dic,
    company_name: exampleContacts[4].company_name,
    street: exampleContacts[4].street,
    city: exampleContacts[4].city,
    postal_code: exampleContacts[4].postal_code,
    phone: exampleContacts[4].phone,
    email: exampleContacts[4].email,
    note: "Buy cash – circulation pumps and nádoby",
  },
  {
    number: "0016",
    type: 1,
    date_issue: "2025-05-16",
    date_tax: "2025-05-16",
    ico: anonymousContacts[0].ico,
    modifier: anonymousContacts[0].modifier,
    dic: anonymousContacts[0].dic,
    company_name: anonymousContacts[0].company_name,
    street: anonymousContacts[0].street,
    city: anonymousContacts[0].city,
    postal_code: anonymousContacts[0].postal_code,
    phone: anonymousContacts[0].phone,
    email: anonymousContacts[0].email,
    note: "Buy cash – mix of pressure pumps and hadice",
  },
  {
    number: "0017",
    type: 1,
    date_issue: "2025-05-17",
    date_tax: "2025-05-17",
    ico: anonymousContacts[1].ico,
    modifier: anonymousContacts[1].modifier,
    dic: anonymousContacts[1].dic,
    company_name: anonymousContacts[1].company_name,
    street: anonymousContacts[1].street,
    city: anonymousContacts[1].city,
    postal_code: anonymousContacts[1].postal_code,
    phone: anonymousContacts[1].phone,
    email: anonymousContacts[1].email,
    note: "Buy cash – delivery of hydropump components",
  },
  {
    number: "0018",
    type: 1,
    date_issue: "2025-05-18",
    date_tax: "2025-05-18",
    ico: anonymousContacts[2].ico,
    modifier: anonymousContacts[2].modifier,
    dic: anonymousContacts[2].dic,
    company_name: anonymousContacts[2].company_name,
    street: anonymousContacts[2].street,
    city: anonymousContacts[2].city,
    postal_code: anonymousContacts[2].postal_code,
    phone: anonymousContacts[2].phone,
    email: anonymousContacts[2].email,
    note: "Buy cash – techflow service parts",
  },
  {
    number: "0019",
    type: 1,
    date_issue: "2025-05-19",
    date_tax: "2025-05-19",
    ico: anonymousContacts[3].ico,
    modifier: anonymousContacts[3].modifier,
    dic: anonymousContacts[3].dic,
    company_name: anonymousContacts[3].company_name,
    street: anonymousContacts[3].street,
    city: anonymousContacts[3].city,
    postal_code: anonymousContacts[3].postal_code,
    phone: anonymousContacts[3].phone,
    email: anonymousContacts[3].email,
    note: "Buy cash – VODATECH bulk accessories",
  },
  {
    number: "0020",
    type: 1,
    date_issue: "2025-05-20",
    date_tax: "2025-05-20",
    ico: anonymousContacts[4].ico,
    modifier: anonymousContacts[4].modifier,
    dic: anonymousContacts[4].dic,
    company_name: anonymousContacts[4].company_name,
    street: anonymousContacts[4].street,
    city: anonymousContacts[4].city,
    postal_code: anonymousContacts[4].postal_code,
    phone: anonymousContacts[4].phone,
    email: anonymousContacts[4].email,
    note: "Buy cash – ČERPADLOEXPORT supply set",
  },

    // ─────────────────────────────
  // TYPE 2 – Buy Invoices (Suppliers, bank)
  // ─────────────────────────────
  {
    number: "0021",
    type: 2,
    payment_method: 1,
    date_issue: "2025-05-21",
    date_tax: "2025-05-21",
    date_due: "2025-06-04",
    variable_symbol: "20250021",
    ico: exampleContacts[5].ico,
    modifier: exampleContacts[5].modifier,
    dic: exampleContacts[5].dic,
    company_name: exampleContacts[5].company_name,
    street: exampleContacts[5].street,
    city: exampleContacts[5].city,
    postal_code: exampleContacts[5].postal_code,
    phone: exampleContacts[5].phone,
    email: exampleContacts[5].email,
    note: "Buy invoice – garden pump series for summer sales",
  },
  {
    number: "0022",
    type: 2,
    payment_method: 1,
    date_issue: "2025-05-22",
    date_tax: "2025-05-22",
    date_due: "2025-06-05",
    variable_symbol: "20250022",
    ico: exampleContacts[6].ico,
    modifier: exampleContacts[6].modifier,
    dic: exampleContacts[6].dic,
    company_name: exampleContacts[6].company_name,
    street: exampleContacts[6].street,
    city: exampleContacts[6].city,
    postal_code: exampleContacts[6].postal_code,
    phone: exampleContacts[6].phone,
    email: exampleContacts[6].email,
    note: "Buy invoice – Zahradnictví stock for promo season",
  },
  {
    number: "0023",
    type: 2,
    payment_method: 1,
    date_issue: "2025-05-23",
    date_tax: "2025-05-23",
    date_due: "2025-06-06",
    variable_symbol: "20250023",
    ico: anonymousContacts[5].ico,
    modifier: anonymousContacts[5].modifier,
    dic: anonymousContacts[5].dic,
    company_name: anonymousContacts[5].company_name,
    street: anonymousContacts[5].street,
    city: anonymousContacts[5].city,
    postal_code: anonymousContacts[5].postal_code,
    phone: anonymousContacts[5].phone,
    email: anonymousContacts[5].email,
    note: "Buy invoice – MONTAPUMP delivery of industrial pumps",
  },
  {
    number: "0024",
    type: 2,
    payment_method: 1,
    date_issue: "2025-05-24",
    date_tax: "2025-05-24",
    date_due: "2025-06-07",
    variable_symbol: "20250024",
    ico: anonymousContacts[6].ico,
    modifier: anonymousContacts[6].modifier,
    dic: anonymousContacts[6].dic,
    company_name: anonymousContacts[6].company_name,
    street: anonymousContacts[6].street,
    city: anonymousContacts[6].city,
    postal_code: anonymousContacts[6].postal_code,
    phone: anonymousContacts[6].phone,
    email: anonymousContacts[6].email,
    note: "Buy invoice – large order of Tlaková čerpadla",
  },
  {
    number: "0025",
    type: 2,
    payment_method: 1,
    date_issue: "2025-05-25",
    date_tax: "2025-05-25",
    date_due: "2025-06-09",
    variable_symbol: "20250025",
    ico: anonymousContacts[7].ico,
    modifier: anonymousContacts[7].modifier,
    dic: anonymousContacts[7].dic,
    company_name: anonymousContacts[7].company_name,
    street: anonymousContacts[7].street,
    city: anonymousContacts[7].city,
    postal_code: anonymousContacts[7].postal_code,
    phone: anonymousContacts[7].phone,
    email: anonymousContacts[7].email,
    note: "Buy invoice – PumpServis regular maintenance parts",
  },
  {
    number: "0026",
    type: 2,
    payment_method: 1,
    date_issue: "2025-05-26",
    date_tax: "2025-05-26",
    date_due: "2025-06-10",
    variable_symbol: "20250026",
    ico: anonymousContacts[8].ico,
    modifier: anonymousContacts[8].modifier,
    dic: anonymousContacts[8].dic,
    company_name: anonymousContacts[8].company_name,
    street: anonymousContacts[8].street,
    city: anonymousContacts[8].city,
    postal_code: anonymousContacts[8].postal_code,
    phone: anonymousContacts[8].phone,
    email: anonymousContacts[8].email,
    note: "Buy invoice – Hydroservis Morava pressure tanks",
  },
  {
    number: "0027",
    type: 2,
    payment_method: 1,
    date_issue: "2025-05-27",
    date_tax: "2025-05-27",
    date_due: "2025-06-11",
    variable_symbol: "20250027",
    ico: anonymousContacts[9].ico,
    modifier: anonymousContacts[9].modifier,
    dic: anonymousContacts[9].dic,
    company_name: anonymousContacts[9].company_name,
    street: anonymousContacts[9].street,
    city: anonymousContacts[9].city,
    postal_code: anonymousContacts[9].postal_code,
    phone: anonymousContacts[9].phone,
    email: anonymousContacts[9].email,
    note: "Buy invoice – Vodoinstalace K&K accessories",
  },
  {
    number: "0028",
    type: 2,
    payment_method: 1,
    date_issue: "2025-05-28",
    date_tax: "2025-05-28",
    date_due: "2025-06-12",
    variable_symbol: "20250028",
    ico: exampleContacts[16].ico,
    modifier: exampleContacts[16].modifier,
    dic: exampleContacts[16].dic,
    company_name: exampleContacts[16].company_name,
    street: exampleContacts[16].street,
    city: exampleContacts[16].city,
    postal_code: exampleContacts[16].postal_code,
    phone: exampleContacts[16].phone,
    email: exampleContacts[16].email,
    note: "Buy invoice – Servisní centrum PUMPY components",
  },
  {
    number: "0029",
    type: 2,
    payment_method: 1,
    date_issue: "2025-05-29",
    date_tax: "2025-05-29",
    date_due: "2025-06-13",
    variable_symbol: "20250029",
    ico: exampleContacts[15].ico,
    modifier: exampleContacts[15].modifier,
    dic: exampleContacts[15].dic,
    company_name: exampleContacts[15].company_name,
    street: exampleContacts[15].street,
    city: exampleContacts[15].city,
    postal_code: exampleContacts[15].postal_code,
    phone: exampleContacts[15].phone,
    email: exampleContacts[15].email,
    note: "Buy invoice – AQUA stavby building-related pumps",
  },
  {
    number: "0030",
    type: 2,
    payment_method: 1,
    date_issue: "2025-05-30",
    date_tax: "2025-05-30",
    date_due: "2025-06-14",
    variable_symbol: "20250030",
    ico: exampleContacts[14].ico,
    modifier: exampleContacts[14].modifier,
    dic: exampleContacts[14].dic,
    company_name: exampleContacts[14].company_name,
    street: exampleContacts[14].street,
    city: exampleContacts[14].city,
    postal_code: exampleContacts[14].postal_code,
    phone: exampleContacts[14].phone,
    email: exampleContacts[14].email,
    note: "Buy invoice – Rodinné domy MODERNÍ pump systems",
  },

 // ─────────────────────────────
  // TYPE 3 – Sell Cash Invoices (Customers, cash)
  // ─────────────────────────────
  {
    number: "0031",
    type: 3,
    date_issue: "2025-05-31",
    date_tax: "2025-05-31",
    ico: exampleContacts[6].ico,
    modifier: exampleContacts[6].modifier,
    dic: exampleContacts[6].dic,
    company_name: exampleContacts[6].company_name,
    street: exampleContacts[6].street,
    city: exampleContacts[6].city,
    postal_code: exampleContacts[6].postal_code,
    phone: exampleContacts[6].phone,
    email: exampleContacts[6].email,
    note: "Sell cash – small delivery for Zahradnictví Zelený svět",
  },
  {
    number: "0032",
    type: 3,
    date_issue: "2025-06-01",
    date_tax: "2025-06-01",
    ico: exampleContacts[7].ico,
    modifier: exampleContacts[7].modifier,
    dic: exampleContacts[7].dic,
    company_name: exampleContacts[7].company_name,
    street: exampleContacts[7].street,
    city: exampleContacts[7].city,
    postal_code: exampleContacts[7].postal_code,
    phone: exampleContacts[7].phone,
    email: exampleContacts[7].email,
    note: "Sell cash – Betonstav order (1-day delivery)",
  },
  {
    number: "0033",
    type: 3,
    date_issue: "2025-06-02",
    date_tax: "2025-06-02",
    ico: exampleContacts[8].ico,
    modifier: exampleContacts[8].modifier,
    dic: exampleContacts[8].dic,
    company_name: exampleContacts[8].company_name,
    street: exampleContacts[8].street,
    city: exampleContacts[8].city,
    postal_code: exampleContacts[8].postal_code,
    phone: exampleContacts[8].phone,
    email: exampleContacts[8].email,
    note: "Sell cash – Autoservis U Honzy s.r.o. accessories",
  },
  {
    number: "0034",
    type: 3,
    date_issue: "2025-06-03",
    date_tax: "2025-06-03",
    ico: exampleContacts[9].ico,
    modifier: exampleContacts[9].modifier,
    dic: exampleContacts[9].dic,
    company_name: exampleContacts[9].company_name,
    street: exampleContacts[9].street,
    city: exampleContacts[9].city,
    postal_code: exampleContacts[9].postal_code,
    phone: exampleContacts[9].phone,
    email: exampleContacts[9].email,
    note: "Sell cash – Bazénová technika AQUA retail sale",
  },
  {
    number: "0035",
    type: 3,
    date_issue: "2025-06-04",
    date_tax: "2025-06-04",
    ico: anonymousContacts[10].ico,
    modifier: anonymousContacts[10].modifier,
    dic: anonymousContacts[10].dic,
    company_name: anonymousContacts[10].company_name,
    street: anonymousContacts[10].street,
    city: anonymousContacts[10].city,
    postal_code: anonymousContacts[10].postal_code,
    phone: anonymousContacts[10].phone,
    email: anonymousContacts[10].email,
    note: "Sell cash – NOVAKO construction supplies",
  },
  {
    number: "0036",
    type: 3,
    date_issue: "2025-06-05",
    date_tax: "2025-06-05",
    ico: anonymousContacts[11].ico,
    modifier: anonymousContacts[11].modifier,
    dic: anonymousContacts[11].dic,
    company_name: anonymousContacts[11].company_name,
    street: anonymousContacts[11].street,
    city: anonymousContacts[11].city,
    postal_code: anonymousContacts[11].postal_code,
    phone: anonymousContacts[11].phone,
    email: anonymousContacts[11].email,
    note: "Sell cash – Zahrady Krásno pump installation",
  },
  {
    number: "0037",
    type: 3,
    date_issue: "2025-06-06",
    date_tax: "2025-06-06",
    ico: anonymousContacts[12].ico,
    modifier: anonymousContacts[12].modifier,
    dic: anonymousContacts[12].dic,
    company_name: anonymousContacts[12].company_name,
    street: anonymousContacts[12].street,
    city: anonymousContacts[12].city,
    postal_code: anonymousContacts[12].postal_code,
    phone: anonymousContacts[12].phone,
    email: anonymousContacts[12].email,
    note: "Sell cash – Hotel Panorama pump replacement",
  },
  {
    number: "0038",
    type: 3,
    date_issue: "2025-06-07",
    date_tax: "2025-06-07",
    ico: anonymousContacts[13].ico,
    modifier: anonymousContacts[13].modifier,
    dic: anonymousContacts[13].dic,
    company_name: anonymousContacts[13].company_name,
    street: anonymousContacts[13].street,
    city: anonymousContacts[13].city,
    postal_code: anonymousContacts[13].postal_code,
    phone: anonymousContacts[13].phone,
    email: anonymousContacts[13].email,
    note: "Sell cash – Zemědělské družstvo Morava spare parts",
  },
  {
    number: "0039",
    type: 3,
    date_issue: "2025-06-08",
    date_tax: "2025-06-08",
    ico: anonymousContacts[14].ico,
    modifier: anonymousContacts[14].modifier,
    dic: anonymousContacts[14].dic,
    company_name: anonymousContacts[14].company_name,
    street: anonymousContacts[14].street,
    city: anonymousContacts[14].city,
    postal_code: anonymousContacts[14].postal_code,
    phone: anonymousContacts[14].phone,
    email: anonymousContacts[14].email,
    note: "Sell cash – Autoservis Karviná tool package",
  },
  {
    number: "0040",
    type: 3,
    date_issue: "2025-06-09",
    date_tax: "2025-06-09",
    ico: anonymousContacts[15].ico,
    modifier: anonymousContacts[15].modifier,
    dic: anonymousContacts[15].dic,
    company_name: anonymousContacts[15].company_name,
    street: anonymousContacts[15].street,
    city: anonymousContacts[15].city,
    postal_code: anonymousContacts[15].postal_code,
    phone: anonymousContacts[15].phone,
    email: anonymousContacts[15].email,
    note: "Sell cash – Zemní práce TESAŘ project delivery",
  },


  // ─────────────────────────────
  // TYPE 4 – Sell Invoices (Customers, bank)
  // ─────────────────────────────
  {
    number: "0041",
    type: 4,
    payment_method: 1,
    date_issue: "2025-06-10",
    date_tax: "2025-06-10",
    date_due: "2025-06-24",
    variable_symbol: "20250041",
    ico: anonymousContacts[16].ico,
    modifier: anonymousContacts[16].modifier,
    dic: anonymousContacts[16].dic,
    company_name: anonymousContacts[16].company_name,
    street: anonymousContacts[16].street,
    city: anonymousContacts[16].city,
    postal_code: anonymousContacts[16].postal_code,
    phone: anonymousContacts[16].phone,
    email: anonymousContacts[16].email,
    note: "Sell invoice – Farma Sever supply of čerpadla",
  },
  {
    number: "0042",
    type: 4,
    payment_method: 1,
    date_issue: "2025-06-11",
    date_tax: "2025-06-11",
    date_due: "2025-06-25",
    variable_symbol: "20250042",
    ico: anonymousContacts[17].ico,
    modifier: anonymousContacts[17].modifier,
    dic: anonymousContacts[17].dic,
    company_name: anonymousContacts[17].company_name,
    street: anonymousContacts[17].street,
    city: anonymousContacts[17].city,
    postal_code: anonymousContacts[17].postal_code,
    phone: anonymousContacts[17].phone,
    email: anonymousContacts[17].email,
    note: "Sell invoice – Zahradnictví Modrá růže retail order",
  },
  {
    number: "0043",
    type: 4,
    payment_method: 1,
    date_issue: "2025-06-12",
    date_tax: "2025-06-12",
    date_due: "2025-06-26",
    variable_symbol: "20250043",
    ico: anonymousContacts[18].ico,
    modifier: anonymousContacts[18].modifier,
    dic: anonymousContacts[18].dic,
    company_name: anonymousContacts[18].company_name,
    street: anonymousContacts[18].street,
    city: anonymousContacts[18].city,
    postal_code: anonymousContacts[18].postal_code,
    phone: anonymousContacts[18].phone,
    email: anonymousContacts[18].email,
    note: "Sell invoice – Stavebniny UH equipment order",
  },
  {
    number: "0044",
    type: 4,
    payment_method: 1,
    date_issue: "2025-06-13",
    date_tax: "2025-06-13",
    date_due: "2025-06-27",
    variable_symbol: "20250044",
    ico: anonymousContacts[19].ico,
    modifier: anonymousContacts[19].modifier,
    dic: anonymousContacts[19].dic,
    company_name: anonymousContacts[19].company_name,
    street: anonymousContacts[19].street,
    city: anonymousContacts[19].city,
    postal_code: anonymousContacts[19].postal_code,
    phone: anonymousContacts[19].phone,
    email: anonymousContacts[19].email,
    note: "Sell invoice – EKOHOUSE delivery of pump units",
  },
  {
    number: "0045",
    type: 4,
    payment_method: 1,
    date_issue: "2025-06-14",
    date_tax: "2025-06-14",
    date_due: "2025-06-28",
    variable_symbol: "20250045",
    ico: exampleContacts[17].ico,
    modifier: exampleContacts[17].modifier,
    dic: exampleContacts[17].dic,
    company_name: exampleContacts[17].company_name,
    street: exampleContacts[17].street,
    city: exampleContacts[17].city,
    postal_code: exampleContacts[17].postal_code,
    phone: exampleContacts[17].phone,
    email: exampleContacts[17].email,
    note: "Sell invoice – TECH-INSTAL a.s. – assembly components",
  },
  {
    number: "0046",
    type: 4,
    payment_method: 1,
    date_issue: "2025-06-15",
    date_tax: "2025-06-15",
    date_due: "2025-06-29",
    variable_symbol: "20250046",
    ico: exampleContacts[18].ico,
    modifier: exampleContacts[18].modifier,
    dic: exampleContacts[18].dic,
    company_name: exampleContacts[18].company_name,
    street: exampleContacts[18].street,
    city: exampleContacts[18].city,
    postal_code: exampleContacts[18].postal_code,
    phone: exampleContacts[18].phone,
    email: exampleContacts[18].email,
    note: "Sell invoice – Vodoinstalace PROFI project materials",
  },
  {
    number: "0047",
    type: 4,
    payment_method: 1,
    date_issue: "2025-06-16",
    date_tax: "2025-06-16",
    date_due: "2025-06-30",
    variable_symbol: "20250047",
    ico: exampleContacts[19].ico,
    modifier: exampleContacts[19].modifier,
    dic: exampleContacts[19].dic,
    company_name: exampleContacts[19].company_name,
    street: exampleContacts[19].street,
    city: exampleContacts[19].city,
    postal_code: exampleContacts[19].postal_code,
    phone: exampleContacts[19].phone,
    email: exampleContacts[19].email,
    note: "Sell invoice – Servisní centrum PUMPY annual delivery",
  },
  {
    number: "0048",
    type: 4,
    payment_method: 1,
    date_issue: "2025-06-17",
    date_tax: "2025-06-17",
    date_due: "2025-07-01",
    variable_symbol: "20250048",
    ico: exampleContacts[10].ico,
    modifier: exampleContacts[10].modifier,
    dic: exampleContacts[10].dic,
    company_name: exampleContacts[10].company_name,
    street: exampleContacts[10].street,
    city: exampleContacts[10].city,
    postal_code: exampleContacts[10].postal_code,
    phone: exampleContacts[10].phone,
    email: exampleContacts[10].email,
    note: "Sell invoice – Hotel Slunce maintenance pumps",
  },
  {
    number: "0049",
    type: 4,
    payment_method: 1,
    date_issue: "2025-06-18",
    date_tax: "2025-06-18",
    date_due: "2025-07-02",
    variable_symbol: "20250049",
    ico: exampleContacts[11].ico,
    modifier: exampleContacts[11].modifier,
    dic: exampleContacts[11].dic,
    company_name: exampleContacts[11].company_name,
    street: exampleContacts[11].street,
    city: exampleContacts[11].city,
    postal_code: exampleContacts[11].postal_code,
    phone: exampleContacts[11].phone,
    email: exampleContacts[11].email,
    note: "Sell invoice – Průmyslové haly CENTRUM project",
  },
  {
    number: "0050",
    type: 4,
    payment_method: 1,
    date_issue: "2025-06-19",
    date_tax: "2025-06-19",
    date_due: "2025-07-03",
    variable_symbol: "20250050",
    ico: exampleContacts[12].ico,
    modifier: exampleContacts[12].modifier,
    dic: exampleContacts[12].dic,
    company_name: exampleContacts[12].company_name,
    street: exampleContacts[12].street,
    city: exampleContacts[12].city,
    postal_code: exampleContacts[12].postal_code,
    phone: exampleContacts[12].phone,
    email: exampleContacts[12].email,
    note: "Sell invoice – Autoumývárna FRESH equipment delivery",
  },
];
