/**
 * Test data generator for KrezBooks
 * Creates realistic Czech water pump business data
 */


/**
 * Generate valid IČO with checksum
 */
function generateValidICO(base: string): string {
  const weights = [8, 7, 6, 5, 4, 3, 2];
  let sum = 0;
  
  for (let i = 0; i < 7; i++) {
    sum += parseInt(base[i], 10) * weights[i];
  }
  
  const mod = sum % 11;
  const check = mod === 0 ? 1 : mod === 1 ? 0 : 11 - mod;
  
  return base + check.toString();
}

/**
 * Test contacts - Czech water pump suppliers and customers
 */
export const testContacts = [
  {
    ico: generateValidICO('2567891'),
    modifier: 1,
    dic: 'CZ25678912',
    company_name: 'PUMPY-SERVIS s.r.o.',
    representative_name: 'Jan Novák',
    street: 'Průmyslová 245',
    city: 'Praha',
    postal_code: '190 00',
    phone: '+420603123456',
    email: 'info@pumpy-servis.cz',
    website: 'www.pumpy-servis.cz',
    bank_account: '123456789/0100',
    is_supplier: true,
    is_customer: false,
    price_group: 1,
  },
  {
    ico: generateValidICO('3456789'),
    modifier: 1,
    dic: 'CZ34567891',
    company_name: 'AQUA TECH spol. s r.o.',
    representative_name: 'Marie Dvořáková',
    street: 'Vodní 89',
    city: 'Brno',
    postal_code: '602 00',
    phone: '+420605234567',
    email: 'obchod@aquatech.cz',
    website: 'www.aquatech.cz',
    bank_account: '987654321/0300',
    is_supplier: true,
    is_customer: false,
    price_group: 1,
  },
  {
    ico: generateValidICO('4567890'),
    modifier: 1,
    dic: 'CZ45678901',
    company_name: 'HYDRO KOMPLET a.s.',
    representative_name: 'Petr Svoboda',
    street: 'Hlavní 156',
    city: 'Ostrava',
    postal_code: '708 00',
    phone: '+420607345678',
    email: 'sales@hydrokomplet.cz',
    website: 'www.hydrokomplet.cz',
    bank_account: '246813579/0600',
    is_supplier: true,
    is_customer: false,
    price_group: 1,
  },
  {
    ico: generateValidICO('5678901'),
    modifier: 1,
    dic: 'CZ56789012',
    company_name: 'ČERPADLA CENTRUM s.r.o.',
    representative_name: 'Jana Procházková',
    street: 'Nádražní 67',
    city: 'Plzeň',
    postal_code: '301 00',
    phone: '+420608456789',
    email: 'info@cerpadlacentrum.cz',
    website: 'www.cerpadlacentrum.cz',
    bank_account: '135792468/0800',
    is_supplier: true,
    is_customer: false,
    price_group: 1,
  },
  {
    ico: generateValidICO('6789012'),
    modifier: 1,
    dic: 'CZ67890123',
    company_name: 'VODOVODNÍ TECHNIKA s.r.o.',
    representative_name: 'Tomáš Veselý',
    street: 'Riegrova 234',
    city: 'Olomouc',
    postal_code: '779 00',
    phone: '+420609567890',
    email: 'obchod@vodovodni-technika.cz',
    website: 'www.vodovodni-technika.cz',
    bank_account: '369258147/2010',
    is_supplier: true,
    is_customer: false,
    price_group: 1,
  },
  
  // Customers
  {
    ico: generateValidICO('7890123'),
    modifier: 1,
    dic: 'CZ78901234',
    company_name: 'Farma Lipůvka s.r.o.',
    representative_name: 'Karel Horák',
    street: 'Lipůvka 12',
    city: 'Benešov',
    postal_code: '256 01',
    phone: '+420721123456',
    email: 'farma@lipuvka.cz',
    website: 'www.farmalipuvka.cz',
    bank_account: '741852963/0100',
    is_supplier: false,
    is_customer: true,
    price_group: 2,
  },
  {
    ico: generateValidICO('8901234'),
    modifier: 1,
    dic: 'CZ89012345',
    company_name: 'Zahradnictví Zelený svět',
    representative_name: 'Eva Malá',
    street: 'Zahradní 45',
    city: 'Hradec Králové',
    postal_code: '500 02',
    phone: '+420722234567',
    email: 'info@zelenysvet.cz',
    website: 'www.zelenysvet.cz',
    bank_account: '852963741/0300',
    is_supplier: false,
    is_customer: true,
    price_group: 3,
  },
  {
    ico: generateValidICO('9012345'),
    modifier: 1,
    dic: 'CZ90123456',
    company_name: 'Stavební firma BETONSTAV',
    representative_name: 'Miroslav Černý',
    street: 'Stavební 789',
    city: 'Liberec',
    postal_code: '460 01',
    phone: '+420723345678',
    email: 'info@betonstav.cz',
    website: 'www.betonstav.cz',
    bank_account: '963741852/0600',
    is_supplier: false,
    is_customer: true,
    price_group: 1,
  },
  {
    ico: generateValidICO('1234567'),
    modifier: 1,
    dic: 'CZ12345678',
    company_name: 'Autoservis U Honzy s.r.o.',
    representative_name: 'Jan Král',
    street: 'Automobilová 23',
    city: 'České Budějovice',
    postal_code: '370 01',
    phone: '+420724456789',
    email: 'servis@uhonzy.cz',
    website: 'www.autoservis-uhonzy.cz',
    bank_account: '147258369/0800',
    is_supplier: false,
    is_customer: true,
    price_group: 2,
  },
  {
    ico: generateValidICO('2345678'),
    modifier: 1,
    company_name: 'Bazénová technika AQUA',
    representative_name: 'Lenka Nová',
    street: 'Sportovní 156',
    city: 'Pardubice',
    postal_code: '530 02',
    phone: '+420725567890',
    email: 'info@bazenova-aqua.cz',
    website: 'www.bazenova-aqua.cz',
    bank_account: '258369147/2010',
    is_supplier: false,
    is_customer: true,
    price_group: 3,
  },
  {
    ico: generateValidICO('3456781'),
    modifier: 1,
    dic: 'CZ34567812',
    company_name: 'Hotel Slunce s.r.o.',
    representative_name: 'David Novotný',
    street: 'Hotelová 89',
    city: 'Karlovy Vary',
    postal_code: '360 01',
    phone: '+420726678901',
    email: 'info@hotelslunce.cz',
    website: 'www.hotelslunce.cz',
    bank_account: '369147258/0100',
    is_supplier: false,
    is_customer: true,
    price_group: 2,
  },
  {
    ico: generateValidICO('4567892'),
    modifier: 1,
    dic: 'CZ45678923',
    company_name: 'Průmyslové haly CENTRUM',
    representative_name: 'Martin Kovář',
    street: 'Průmyslová 567',
    city: 'Zlín',
    postal_code: '760 01',
    phone: '+420727789012',
    email: 'info@prumhaly.cz',
    website: 'www.prumhaly-centrum.cz',
    bank_account: '147369258/0300',
    is_supplier: false,
    is_customer: true,
    price_group: 1,
  },
  {
    ico: generateValidICO('5678903'),
    modifier: 1,
    company_name: 'Autoumývárna FRESH',
    representative_name: 'Petra Růžičková',
    street: 'Mytí 34',
    city: 'Jihlava',
    postal_code: '586 01',
    phone: '+420728890123',
    email: 'kontakt@fresh-umyvarna.cz',
    website: 'www.fresh-umyvarna.cz',
    bank_account: '258147369/0600',
    is_supplier: false,
    is_customer: true,
    price_group: 3,
  },
  {
    ico: generateValidICO('6789014'),
    modifier: 1,
    dic: 'CZ67890145',
    company_name: 'Rodinné domy MODERNÍ',
    representative_name: 'Jakub Procházka',
    street: 'Bytová 123',
    city: 'Teplice',
    postal_code: '415 01',
    phone: '+420729901234',
    email: 'info@rd-moderni.cz',
    website: 'www.rd-moderni.cz',
    bank_account: '369258147/0800',
    is_supplier: false,
    is_customer: true,
    price_group: 2,
  },
  {
    ico: generateValidICO('7890125'),
    modifier: 1,
    dic: 'CZ78901256',
    company_name: 'Čistírna odpadních vod EKOTECH',
    representative_name: 'Michaela Pokorná',
    street: 'Ekologická 78',
    city: 'Přerov',
    postal_code: '750 02',
    phone: '+420730012345',
    email: 'info@cov-ekotech.cz',
    website: 'www.cov-ekotech.cz',
    bank_account: '147258963/2010',
    is_supplier: false,
    is_customer: true,
    price_group: 1,
  },
  
  // Mixed (both supplier and customer)
  {
    ico: generateValidICO('8901236'),
    modifier: 1,
    dic: 'CZ89012367',
    company_name: 'VODOHOSPODÁŘ servis s.r.o.',
    representative_name: 'Roman Bílý',
    street: 'Vodohospodářská 456',
    city: 'Tábor',
    postal_code: '390 01',
    phone: '+420731123456',
    email: 'servis@vodohospodar.cz',
    website: 'www.vodohospodar-servis.cz',
    bank_account: '258963147/0100',
    is_supplier: true,
    is_customer: true,
    price_group: 2,
  },
  {
    ico: generateValidICO('9012347'),
    modifier: 1,
    dic: 'CZ90123478',
    company_name: 'TECH-INSTAL montáže a.s.',
    representative_name: 'Lucie Stejskalová',
    street: 'Montážní 234',
    city: 'Frýdek-Místek',
    postal_code: '738 01',
    phone: '+420732234567',
    email: 'info@tech-instal.cz',
    website: 'www.tech-instal.cz',
    bank_account: '369147852/0300',
    is_supplier: true,
    is_customer: true,
    price_group: 1,
  },
  {
    ico: generateValidICO('1234568'),
    modifier: 1,
    dic: 'CZ12345689',
    company_name: 'Vodoinstalace PROFI',
    representative_name: 'Ondřej Šťastný',
    street: 'Instalační 67',
    city: 'Mladá Boleslav',
    postal_code: '293 01',
    phone: '+420733345678',
    email: 'info@vodoinstalace-profi.cz',
    website: 'www.vodoinstalace-profi.cz',
    bank_account: '147852369/0600',
    is_supplier: true,
    is_customer: true,
    price_group: 3,
  },
  {
    ico: generateValidICO('2345679'),
    modifier: 1,
    company_name: 'AQUA stavby s.r.o.',
    representative_name: 'Simona Křížová',
    street: 'Stavební 890',
    city: 'Děčín',
    postal_code: '405 01',
    phone: '+420734456789',
    email: 'info@aquastavby.cz',
    website: 'www.aquastavby.cz',
    bank_account: '258369741/0800',
    is_supplier: true,
    is_customer: true,
    price_group: 2,
  },
  {
    ico: generateValidICO('3456782'),
    modifier: 1,
    dic: 'CZ34567823',
    company_name: 'Servisní centrum PUMPY',
    representative_name: 'Vladimír Havel',
    street: 'Servisní 123',
    city: 'Chomutov',
    postal_code: '430 01',
    phone: '+420735567890',
    email: 'servis@sc-pumpy.cz',
    website: 'www.serviscentrum-pumpy.cz',
    bank_account: '369741258/2010',
    is_supplier: true,
    is_customer: true,
    price_group: 1,
  },
];

/**
 * Test items - Water pumps and related equipment
 */
export const testItems= [
  // Ponorná čerpadla (Submersible pumps)
  {
    name: 'Ponorné čerpadlo 4" 0,5 HP',
    sales_group: '1',
    note: 'Určeno pro domácí studny, max. hloubka 40m',
    vat_rate: 2,
    avg_purchase_price: 2800,
    last_purchase_price: 2950,
    unit_of_measure: 'ks',
    sale_price_group1: 4200,
    sale_price_group2: 3900,
    sale_price_group3: 3700,
    sale_price_group4: 3500,
  },
  {
    name: 'Ponorné čerpadlo 4" 0,75 HP',
    sales_group: '1',
    note: 'Pro hlubší studny až 60m, vyšší výkon',
    vat_rate: 2,
    avg_purchase_price: 3500,
    last_purchase_price: 3650,
    unit_of_measure: 'ks',
    sale_price_group1: 5200,
    sale_price_group2: 4900,
    sale_price_group3: 4700,
    sale_price_group4: 4500,
  },
  {
    name: 'Ponorné čerpadlo 4" 1 HP nerez',
    sales_group: '1',
    note: 'Nerezové provedení, odolné proti korozi',
    vat_rate: 2,
    avg_purchase_price: 4800,
    last_purchase_price: 5000,
    unit_of_measure: 'ks',
    sale_price_group1: 7200,
    sale_price_group2: 6800,
    sale_price_group3: 6500,
    sale_price_group4: 6200,
  },
  {
    name: 'Ponorné čerpadlo 6" 1,5 HP',
    sales_group: '1',
    note: 'Pro vrty s větším průměrem, vysoký výkon',
    vat_rate: 2,
    avg_purchase_price: 6200,
    last_purchase_price: 6400,
    unit_of_measure: 'ks',
    sale_price_group1: 9300,
    sale_price_group2: 8800,
    sale_price_group3: 8400,
    sale_price_group4: 8000,
  },
  {
    name: 'Ponorné čerpadlo 6" 2 HP průmyslové',
    sales_group: '1',
    note: 'Průmyslové provedení pro náročné podmínky',
    vat_rate: 2,
    avg_purchase_price: 8500,
    last_purchase_price: 8800,
    unit_of_measure: 'ks',
    sale_price_group1: 12750,
    sale_price_group2: 12000,
    sale_price_group3: 11500,
    sale_price_group4: 11000,
  },
  
  // Kalová čerpadla (Sewage pumps)
  {
    name: 'Kalové čerpadlo 400W plastové',
    sales_group: '1',
    note: 'Pro čerpání znečištěné vody, průchod 35mm',
    vat_rate: 2,
    avg_purchase_price: 1800,
    last_purchase_price: 1900,
    unit_of_measure: 'ks',
    sale_price_group1: 2700,
    sale_price_group2: 2500,
    sale_price_group3: 2400,
    sale_price_group4: 2300,
  },
  {
    name: 'Kalové čerpadlo 750W s řezacím zařízením',
    sales_group: '1',
    note: 'Se sekacím zařízením, průchod 50mm',
    vat_rate: 2,
    avg_purchase_price: 3200,
    last_purchase_price: 3350,
    unit_of_measure: 'ks',
    sale_price_group1: 4800,
    sale_price_group2: 4500,
    sale_price_group3: 4300,
    sale_price_group4: 4100,
  },
  {
    name: 'Kalové čerpadlo 1100W nerez',
    sales_group: '1',
    note: 'Nerezové provedení, pro agresivní prostředí',
    vat_rate: 2,
    avg_purchase_price: 4500,
    last_purchase_price: 4700,
    unit_of_measure: 'ks',
    sale_price_group1: 6750,
    sale_price_group2: 6300,
    sale_price_group3: 6000,
    sale_price_group4: 5700,
  },
  {
    name: 'Kalové čerpadlo 1500W průmyslové',
    sales_group: '1',
    note: 'Těžký průmysl, čerpání směsí s pevnými částicemi',
    vat_rate: 2,
    avg_purchase_price: 6800,
    last_purchase_price: 7100,
    unit_of_measure: 'ks',
    sale_price_group1: 10200,
    sale_price_group2: 9600,
    sale_price_group3: 9200,
    sale_price_group4: 8800,
  },
  {
    name: 'Kalové čerpadlo 2200W s plovákový spínačem',
    sales_group: '1',
    note: 'Automatický provoz, průchod 80mm',
    vat_rate: 2,
    avg_purchase_price: 8200,
    last_purchase_price: 8500,
    unit_of_measure: 'ks',
    sale_price_group1: 12300,
    sale_price_group2: 11600,
    sale_price_group3: 11100,
    sale_price_group4: 10600,
  },
  
  // Zahradní čerpadla (Garden pumps)
  {
    name: 'Zahradní čerpadlo 600W samosací',
    sales_group: '2',
    note: 'Pro závlahu zahrad, výkon 3000 l/hod',
    vat_rate: 2,
    avg_purchase_price: 1500,
    last_purchase_price: 1600,
    unit_of_measure: 'ks',
    sale_price_group1: 2250,
    sale_price_group2: 2100,
    sale_price_group3: 2000,
    sale_price_group4: 1900,
  },
  {
    name: 'Zahradní čerpadlo 800W nerez hlava',
    sales_group: '2',
    note: 'Vyšší tlak, vhodné pro postřik',
    vat_rate: 2,
    avg_purchase_price: 2200,
    last_purchase_price: 2300,
    unit_of_measure: 'ks',
    sale_price_group1: 3300,
    sale_price_group2: 3100,
    sale_price_group3: 2950,
    sale_price_group4: 2800,
  },
  {
    name: 'Zahradní čerpadlo 1000W s automatem',
    sales_group: '2',
    note: 'S elektronickým tlakovým spínačem',
    vat_rate: 2,
    avg_purchase_price: 2800,
    last_purchase_price: 2950,
    unit_of_measure: 'ks',
    sale_price_group1: 4200,
    sale_price_group2: 3950,
    sale_price_group3: 3800,
    sale_price_group4: 3600,
  },
  {
    name: 'Zahradní čerpadlo 1200W zahradní automat',
    sales_group: '2',
    note: 'Kompletní zahradní vodárna s 24l nádobou',
    vat_rate: 2,
    avg_purchase_price: 3500,
    last_purchase_price: 3700,
    unit_of_measure: 'ks',
    sale_price_group1: 5250,
    sale_price_group2: 4950,
    sale_price_group3: 4750,
    sale_price_group4: 4500,
  },
  {
    name: 'Zahradní čerpadlo 1500W s filtrem',
    sales_group: '2',
    note: 'Pro čerpání vody z nádrží a rybníků',
    vat_rate: 2,
    avg_purchase_price: 4200,
    last_purchase_price: 4400,
    unit_of_measure: 'ks',
    sale_price_group1: 6300,
    sale_price_group2: 5950,
    sale_price_group3: 5700,
    sale_price_group4: 5400,
  },
  
  // Tlaková čerpadla (Pressure pumps)
  {
    name: 'Tlakové čerpadlo 600W domácí vodárna',
    sales_group: '2',
    note: 'Pro rodinné domy, se 24l tlakovou nádobou',
    vat_rate: 2,
    avg_purchase_price: 2500,
    last_purchase_price: 2650,
    unit_of_measure: 'ks',
    sale_price_group1: 3750,
    sale_price_group2: 3500,
    sale_price_group3: 3350,
    sale_price_group4: 3200,
  },
  {
    name: 'Tlakové čerpadlo 800W s 50l nádobou',
    sales_group: '2',
    note: 'Větší zásobní objem, tišší provoz',
    vat_rate: 2,
    avg_purchase_price: 3800,
    last_purchase_price: 4000,
    unit_of_measure: 'ks',
    sale_price_group1: 5700,
    sale_price_group2: 5350,
    sale_price_group3: 5100,
    sale_price_group4: 4850,
  },
  {
    name: 'Tlakové čerpadlo 1000W s 80l nádobou',
    sales_group: '2',
    note: 'Pro větší odběry, elektronické řízení',
    vat_rate: 2,
    avg_purchase_price: 5200,
    last_purchase_price: 5400,
    unit_of_measure: 'ks',
    sale_price_group1: 7800,
    sale_price_group2: 7350,
    sale_price_group3: 7050,
    sale_price_group4: 6700,
  },
  {
    name: 'Tlakové čerpadlo 1200W se 100l nádobou',
    sales_group: '2',
    note: 'Pro větší objekty, hotel, penzion',
    vat_rate: 2,
    avg_purchase_price: 6500,
    last_purchase_price: 6800,
    unit_of_measure: 'ks',
    sale_price_group1: 9750,
    sale_price_group2: 9200,
    sale_price_group3: 8800,
    sale_price_group4: 8400,
  },
  {
    name: 'Tlakové čerpadlo 1500W frekvenční měnič',
    sales_group: '2',
    note: 'S plynulou regulací výkonu, úspora energie',
    vat_rate: 2,
    avg_purchase_price: 8500,
    last_purchase_price: 8800,
    unit_of_measure: 'ks',
    sale_price_group1: 12750,
    sale_price_group2: 12000,
    sale_price_group3: 11500,
    sale_price_group4: 11000,
  },
  
  // Cirkulační čerpadla (Circulation pumps)
  {
    name: 'Cirkulační čerpadlo 25-40 180mm',
    sales_group: '3',
    note: 'Pro rodinné domy, topení a TUV',
    vat_rate: 2,
    avg_purchase_price: 1200,
    last_purchase_price: 1300,
    unit_of_measure: 'ks',
    sale_price_group1: 1800,
    sale_price_group2: 1700,
    sale_price_group3: 1600,
    sale_price_group4: 1500,
  },
  {
    name: 'Cirkulační čerpadlo 25-60 180mm třístupňové',
    sales_group: '3',
    note: 'Větší výkon, 3 rychlosti',
    vat_rate: 2,
    avg_purchase_price: 1800,
    last_purchase_price: 1900,
    unit_of_measure: 'ks',
    sale_price_group1: 2700,
    sale_price_group2: 2550,
    sale_price_group3: 2450,
    sale_price_group4: 2300,
  },
  {
    name: 'Cirkulační čerpadlo 25-80 180mm vysokotlaké',
    sales_group: '3',
    note: 'Pro vyšší budovy, větší průtok',
    vat_rate: 2,
    avg_purchase_price: 2500,
    last_purchase_price: 2650,
    unit_of_measure: 'ks',
    sale_price_group1: 3750,
    sale_price_group2: 3550,
    sale_price_group3: 3400,
    sale_price_group4: 3200,
  },
  {
    name: 'Cirkulační čerpadlo 32-60 250mm',
    sales_group: '3',
    note: 'Pro průmyslové aplikace, větší průměr',
    vat_rate: 2,
    avg_purchase_price: 3200,
    last_purchase_price: 3400,
    unit_of_measure: 'ks',
    sale_price_group1: 4800,
    sale_price_group2: 4550,
    sale_price_group3: 4350,
    sale_price_group4: 4100,
  },
  {
    name: 'Cirkulační čerpadlo EEI ≤0,23 elektronické',
    sales_group: '3',
    note: 'Energeticky úsporné, s elektronickou regulací',
    vat_rate: 2,
    avg_purchase_price: 4500,
    last_purchase_price: 4700,
    unit_of_measure: 'ks',
    sale_price_group1: 6750,
    sale_price_group2: 6400,
    sale_price_group3: 6100,
    sale_price_group4: 5800,
  },
  
  // Příslušenství (Accessories)
  {
    name: 'Hadice PVC 1" průhledná',
    sales_group: '4',
    note: 'Pro čerpání čisté vody',
    vat_rate: 2,
    avg_purchase_price: 35,
    last_purchase_price: 38,
    unit_of_measure: 'l',
    sale_price_group1: 55,
    sale_price_group2: 52,
    sale_price_group3: 50,
    sale_price_group4: 48,
  },
  {
    name: 'Hadice PVC 1,5" spirálová',
    sales_group: '4',
    note: 'Armovaná, odolná proti podtlaku',
    vat_rate: 2,
    avg_purchase_price: 55,
    last_purchase_price: 58,
    unit_of_measure: 'l',
    sale_price_group1: 85,
    sale_price_group2: 80,
    sale_price_group3: 77,
    sale_price_group4: 74,
  },
  {
    name: 'Hadice PVC 2" plochá',
    sales_group: '4',
    note: 'Pro kalová čerpadla',
    vat_rate: 2,
    avg_purchase_price: 42,
    last_purchase_price: 45,
    unit_of_measure: 'l',
    sale_price_group1: 65,
    sale_price_group2: 62,
    sale_price_group3: 59,
    sale_price_group4: 56,
  },
  {
    name: 'Zpětná klapka 1" mosazná',
    sales_group: '4',
    note: 'Zabraňuje zpětnému toku',
    vat_rate: 2,
    avg_purchase_price: 150,
    last_purchase_price: 160,
    unit_of_measure: 'ks',
    sale_price_group1: 240,
    sale_price_group2: 225,
    sale_price_group3: 215,
    sale_price_group4: 205,
  },
  {
    name: 'Zpětná klapka 1,5" nerezová',
    sales_group: '4',
    note: 'Pro agresivní prostředí',
    vat_rate: 2,
    avg_purchase_price: 280,
    last_purchase_price: 295,
    unit_of_measure: 'ks',
    sale_price_group1: 440,
    sale_price_group2: 415,
    sale_price_group3: 395,
    sale_price_group4: 375,
  },
  {
    name: 'Filtr na vodu 10" s patronou',
    sales_group: '4',
    note: 'Pro mechanické filtrace, 5 mikronů',
    vat_rate: 2,
    avg_purchase_price: 320,
    last_purchase_price: 340,
    unit_of_measure: 'ks',
    sale_price_group1: 510,
    sale_price_group2: 480,
    sale_price_group3: 460,
    sale_price_group4: 435,
  },
  {
    name: 'Náhradní patrona do filtru 10"',
    sales_group: '4',
    note: 'Výměnná vložka, 5 mikronů',
    vat_rate: 2,
    avg_purchase_price: 45,
    last_purchase_price: 48,
    unit_of_measure: 'ks',
    sale_price_group1: 72,
    sale_price_group2: 68,
    sale_price_group3: 65,
    sale_price_group4: 62,
  },
  {
    name: 'Plovákový spínač 3m kabel',
    sales_group: '4',
    note: 'Pro automatické spínání čerpadel',
    vat_rate: 2,
    avg_purchase_price: 180,
    last_purchase_price: 190,
    unit_of_measure: 'ks',
    sale_price_group1: 285,
    sale_price_group2: 270,
    sale_price_group3: 258,
    sale_price_group4: 245,
  },
  {
    name: 'Plovákový spínač 10m kabel',
    sales_group: '4',
    note: 'Pro hlubší nádrže a studny',
    vat_rate: 2,
    avg_purchase_price: 280,
    last_purchase_price: 295,
    unit_of_measure: 'ks',
    sale_price_group1: 440,
    sale_price_group2: 415,
    sale_price_group3: 395,
    sale_price_group4: 375,
  },
  {
    name: 'Tlakový spínač PM/5 230V',
    sales_group: '4',
    note: 'Pro automatické řízení vodáren',
    vat_rate: 2,
    avg_purchase_price: 220,
    last_purchase_price: 235,
    unit_of_measure: 'ks',
    sale_price_group1: 350,
    sale_price_group2: 330,
    sale_price_group3: 315,
    sale_price_group4: 300,
  },
  {
    name: 'Elektronický tlakový spínač',
    sales_group: '4',
    note: 'Ochrana proti běhu nasucho',
    vat_rate: 2,
    avg_purchase_price: 650,
    last_purchase_price: 680,
    unit_of_measure: 'ks',
    sale_price_group1: 1020,
    sale_price_group2: 965,
    sale_price_group3: 920,
    sale_price_group4: 875,
  },
  {
    name: 'Tlaková nádoba 24l horizontální',
    sales_group: '4',
    note: 'Pro domácí vodárny',
    vat_rate: 2,
    avg_purchase_price: 420,
    last_purchase_price: 440,
    unit_of_measure: 'ks',
    sale_price_group1: 660,
    sale_price_group2: 625,
    sale_price_group3: 595,
    sale_price_group4: 565,
  },
  {
    name: 'Tlaková nádoba 50l vertikální',
    sales_group: '4',
    note: 'Větší objem, šetří místo',
    vat_rate: 2,
    avg_purchase_price: 780,
    last_purchase_price: 820,
    unit_of_measure: 'ks',
    sale_price_group1: 1230,
    sale_price_group2: 1165,
    sale_price_group3: 1110,
    sale_price_group4: 1055,
  },
  {
    name: 'Tlaková nádoba 100l horizontální',
    sales_group: '4',
    note: 'Pro větší systémy',
    vat_rate: 2,
    avg_purchase_price: 1450,
    last_purchase_price: 1520,
    unit_of_measure: 'ks',
    sale_price_group1: 2280,
    sale_price_group2: 2160,
    sale_price_group3: 2060,
    sale_price_group4: 1960,
  },
  {
    name: 'Manometr 0-6 bar 1/4"',
    sales_group: '4',
    note: 'Pro kontrolu tlaku v systému',
    vat_rate: 2,
    avg_purchase_price: 65,
    last_purchase_price: 70,
    unit_of_measure: 'ks',
    sale_price_group1: 105,
    sale_price_group2: 99,
    sale_price_group3: 95,
    sale_price_group4: 90,
  },
  {
    name: 'Pojistný ventil 6 bar 1/2"',
    sales_group: '4',
    note: 'Ochrana proti přetlaku',
    vat_rate: 2,
    avg_purchase_price: 120,
    last_purchase_price: 128,
    unit_of_measure: 'ks',
    sale_price_group1: 192,
    sale_price_group2: 182,
    sale_price_group3: 173,
    sale_price_group4: 164,
  },
];